# Generated by Django 4.2.3 on 2023-07-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evote', models.IntegerField(default=0)),
                ('mvote', models.IntegerField(default=0)),
                ('dvote', models.IntegerField(default=0)),
                ('ivote', models.IntegerField(default=0)),
                ('dsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='dsa.dsa')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('dsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='dsa.dsa')),
            ],
        ),
    ]
